--A View stores a SQL query, not the actual table data.
--A VIEW IS CREATE A VIRTUAL TABLE BASED ON THE RESULT SET OF A SQL QUERY.

EXAMPLE:
CREATE VIEW EMPLOYEE_VIEW AS
FROM EMPLOYEE 
WHERE SALARY > 50000;

PROBLEM1: Create a view to display employee name, department, and salary.
QUERY:
CTREATE VIEW EMPLOYEE_DEPT_VIEW AS
SELECT NAME, DEPARTMENT_NAME, SALARY
FROM EMPLOYEE ;

PROBLEM2: Create a view to display employees with salary greater than the average salary.
QUERY:
CREATE VIEW HIGH_SALARY_EMPLOYEES AS
SELECT NAME,SALARY
FROM EMPLOYEE
WHERE SAALARY > (
    SELECT AVG(SALARY) FROM EMPLOYEE
);

PROBLEM3: Create a view to display the total salary paid to each department.
QUERY:
CREATE VIEW DEPARTMENT_SALARY_VIEW AS
SELECT DEPARTMENT_NAME, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE   
GROUP BY DEPARTMENT_NAME;

PROBLEM4: Create a view to display employees along with their department names.
QUERY:
CREATE VIEW EMPLOYEE_DEPARTMENT_VIEW AS
SELECT e.NAME, d.DEPARTMENT_NAME
FROM EMPLOYEE e
INNER JOIN DEPARTMENT d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

PROBLEM5: Create a view to display employees with the second-highest salary.
QUERY:
CREATE VIEW SECOND_HIGHEST_SALARY_EMPLOYEES AS
SELECT * FROM EMPLOYEE
WHERE SALARY =(
    SELECT MAX(SALARY) FROMEMPLOYEE 
    WHERE SALARY <(
        SELECT MAX(SALARY) FROM EMPLOYEE
    )
);
PROBLEM6:Create a view that displays departments having more than 2 employees.
QUERY:
CREATE VIEW DEPARTMENTS_WITH_MORE_THAN_2_EMPLOYEES AS
SELECT DEPARTMENT_NAME, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEE
GROUP BY DEPARTMENT_NAME
HAVING COUNT(*) > 2;
